name: jobbed
description: Jobbed

version: 1.0.2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  flutter_secure_storage: ^3.3.3
  fluttertoast: ^4.0.0
  countup: ^0.1.0
  open_appstore: ^1.0.2
  url_launcher: ^5.4.2
  pin_code_text_field: ^1.7.1
  form_field_validator: ^1.0.1
  dropdown_formfield: ^0.1.2
  slide_popup_dialog: ^0.0.2
  date_range_picker: ^1.0.6
  date_util: ^0.1.4
  intl: ^0.16.0
  bouncing_widget: ^1.2.0
  shimmer: ^1.1.1
  table_calendar: ^2.2.3
  month_picker_dialog: ^0.2.3
  google_maps_flutter: ^1.0.6
  place_picker: ^0.9.17
  geolocator: ^6.1.6
  syncfusion_flutter_sliders: ^18.3.48-beta
  location: ^2.3.5
  permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  number_inc_dec: ^0.6.6
  flutter_progress_dialog: ^0.1.0
  upgrader: ^2.7.3
  xml: ^4.5.1
  flutter_cached_pdfview: ^0.3.1
  draggable_widget: ^1.0.1
  splashscreen: ^1.3.5
  google_fonts: ^1.1.1
  horizontal_data_table: ^1.0.9
  flutter_speed_dial: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "images/logo-icon.png"
  ios: true
  android: true

flutter:

  uses-material-design: true

  assets:
    - lib/internationalization/lang/en.json
    - lib/internationalization/lang/pt.json
    - lib/internationalization/lang/pl.json
    - lib/internationalization/lang/ru.json
    - lib/internationalization/lang/uk.json

    - images/logo.png
    - images/logo-icon.png
    - images/plumko.png
    - images/viber.png
    - images/whatsapp.png
    - images/excel.png

    - images/company.png
    - images/group.png
    - images/groups.png
    - images/work-time.png
    - images/quick-update.png
    - images/timesheet.png
    - images/workplace.png
    - images/manager.png
    - images/employee.png
    - images/contact-with-manager.png
    - images/employee-work.png
    - images/calendar.png
    - images/employees-settings.png
    - images/items.png
    - images/price-list.png
    - images/warehouse.png
    - images/play.png
    - images/stop.png
    - images/hours.png
    - images/piecework.png
    - images/note.png
    - images/white-piecework.png
    - images/white-hours.png
    - images/white-note.png
    - images/white-play.png
    - images/white-stop.png

    - images/letters/male/A.png
    - images/letters/male/B.png
    - images/letters/male/C.png
    - images/letters/male/D.png
    - images/letters/male/E.png
    - images/letters/male/F.png
    - images/letters/male/G.png
    - images/letters/male/H.png
    - images/letters/male/I.png
    - images/letters/male/J.png
    - images/letters/male/K.png
    - images/letters/male/L.png
    - images/letters/male/M.png
    - images/letters/male/N.png
    - images/letters/male/O.png
    - images/letters/male/P.png
    - images/letters/male/Q.png
    - images/letters/male/R.png
    - images/letters/male/S.png
    - images/letters/male/T.png
    - images/letters/male/U.png
    - images/letters/male/V.png
    - images/letters/male/W.png
    - images/letters/male/X.png
    - images/letters/male/Y.png
    - images/letters/male/Z.png
    - images/letters/male/Ł.png
    - images/letters/male/Ż.png
    - images/letters/male/unknown_letter.png

    - images/letters/female/A.png
    - images/letters/female/B.png
    - images/letters/female/C.png
    - images/letters/female/D.png
    - images/letters/female/E.png
    - images/letters/female/F.png
    - images/letters/female/G.png
    - images/letters/female/H.png
    - images/letters/female/I.png
    - images/letters/female/J.png
    - images/letters/female/K.png
    - images/letters/female/L.png
    - images/letters/female/M.png
    - images/letters/female/N.png
    - images/letters/female/O.png
    - images/letters/female/P.png
    - images/letters/female/Q.png
    - images/letters/female/R.png
    - images/letters/female/S.png
    - images/letters/female/T.png
    - images/letters/female/U.png
    - images/letters/female/V.png
    - images/letters/female/W.png
    - images/letters/female/X.png
    - images/letters/female/Y.png
    - images/letters/female/Z.png
    - images/letters/female/Ł.png
    - images/letters/female/Ż.png
    - images/letters/female/unknown_letter.png

    - docs/regulations.pdf
    - docs/privacy_policy.pdf
