name: give_job
description: GiveJob

version: 1.0.13+14

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  flutter_secure_storage: ^3.3.3
  fluttertoast: ^4.0.0
  progress_dialog: ^1.2.4
  countup: ^0.1.0
  open_appstore: ^1.0.2
  url_launcher: ^5.4.2
  pin_code_text_field: ^1.7.1
  form_field_validator: ^1.0.1
  dropdown_formfield: ^0.1.2
  flutter_plugin_pdf_viewer: ^1.0.7
  slide_popup_dialog: ^0.0.2
  date_range_picker: ^1.0.6
  date_util: ^0.1.4
  intl: ^0.16.0
  bouncing_widget: ^1.2.0
  shimmer: ^1.1.1
  table_calendar: ^2.2.3
  month_picker_dialog: ^0.2.3
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.6
  syncfusion_flutter_sliders: ^18.3.48-beta
  location: ^3.0.1
  permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "images/logo.png"
  ios: true
  android: true

flutter:

  uses-material-design: true

  assets:
    - lib/internationalization/lang/be.json
    - lib/internationalization/lang/en.json
    - lib/internationalization/lang/fr.json
    - lib/internationalization/lang/pt.json
    - lib/internationalization/lang/de.json
    - lib/internationalization/lang/ro.json
    - lib/internationalization/lang/nl.json
    - lib/internationalization/lang/it.json
    - lib/internationalization/lang/pl.json
    - lib/internationalization/lang/ru.json
    - lib/internationalization/lang/es.json
    - lib/internationalization/lang/ca.json
    - lib/internationalization/lang/uk.json

    - images/logo.png
    - images/plumko-logo.png
    - images/givejob-medica-logo.png
    - images/facebook-logo.png
    - images/instagram-logo.png
    - images/linkedin-logo.png
    - images/viber-logo.png
    - images/whatsapp-logo.png
    - images/group-img.png
    - images/unchecked.png
    - images/checked.png
    - images/play-icon.png
    - images/stop-icon.png

    - images/company-icon.png
    - images/group-icon.png
    - images/groups-icon.png
    - images/employees-icon.png
    - images/quick_update-icon.png
    - images/timesheets-icon.png
    - images/vocation-icon.png
    - images/workplace-icon.png
    - images/help-icon.png
    - images/documents-icon.png
    - images/manager-icon.png
    - images/employee-icon.png
    - images/contact-with-manager-icon.png
    - images/employee-work-icon.png
    - images/calendar-icon.png
    - images/employees-settings-icon.png

    - images/green-hours-icon.png
    - images/green-rate-icon.png
    - images/green-plan-icon.png
    - images/green-opinion-icon.png
    - images/green-workplace-icon.png
    - images/green-vocation-icon.png

    - images/dark-hours-icon.png
    - images/dark-rate-icon.png
    - images/dark-plan-icon.png
    - images/dark-opinion-icon.png
    - images/dark-workplace-icon.png
    - images/dark-vocation-icon.png

    - docs/regulations.pdf
    - docs/privacy_policy.pdf
