name: jobbed
description: Jobbed

version: 1.0.6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  flutter_secure_storage: ^3.3.3
  countup: ^0.1.0
  open_appstore: ^1.0.2
  url_launcher: ^5.4.2
  pin_code_text_field: ^1.7.1
  form_field_validator: ^1.0.1
  dropdown_formfield: ^0.1.2
  slide_popup_dialog: ^0.0.2
  intl: ^0.16.0
  bouncing_widget: ^1.2.0
  shimmer: ^1.1.1
  table_calendar: ^2.2.3
  month_picker_dialog: ^0.2.3
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.6
  syncfusion_flutter_sliders: ^18.3.48-beta
  location: ^2.3.5
  permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  number_inc_dec: ^0.6.6
  flutter_progress_dialog: ^0.1.0
  upgrader: ^2.7.3
  xml: ^4.5.1
  flutter_cached_pdfview: ^0.3.1
  draggable_widget: ^1.0.1
  splashscreen: ^1.3.5
  horizontal_data_table: ^1.0.9
  flutter_speed_dial: ^1.2.1
  flutter_dropdown: ^0.0.8
  expandable_text: ^1.3.2
  google_map_location_picker: ^4.1.6
  bot_toast: ^3.0.5
  avatar_letter: ^1.0.1
  calendarro: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "images/logo-icon.png"
  ios: true
  android: true

flutter:

  uses-material-design: true

  assets:
    - lib/internationalization/lang/en.json
    - lib/internationalization/lang/pt.json
    - lib/internationalization/lang/pl.json
    - lib/internationalization/lang/ru.json
    - lib/internationalization/lang/uk.json

    - images/logo.png
    - images/logo-icon.png
    - images/plumko.png
    - images/viber.png
    - images/whatsapp.png
    - images/excel.png

    - images/company.png
    - images/group.png
    - images/groups.png
    - images/work-time.png
    - images/quick-update.png
    - images/timesheet.png
    - images/workplace.png
    - images/manager.png
    - images/employee.png
    - images/contact-with-manager.png
    - images/employee-work.png
    - images/calendar.png
    - images/employees-settings.png
    - images/items.png
    - images/price-list.png
    - images/warehouse.png
    - images/play.png
    - images/stop.png
    - images/hours.png
    - images/piecework.png
    - images/disk.png
    - images/note.png
    - images/white-piecework.png
    - images/white-hours.png
    - images/white-note.png
    - images/white-play.png
    - images/white-stop.png

    - docs/regulations.pdf
    - docs/privacy_policy.pdf
